// Inventaire de la sauvegarde (#7) : TOUT modèle du schéma est soit sauvegardé (clé de l'export
// → modèle), soit explicitement exclu avec sa raison. Un test (tests/unit/backup-models.test.ts)
// compare cette liste à Prisma.ModelName : un nouveau modèle oublié fait échouer la suite.

export const BACKUP_MODELS: Record<string, string> = {
  userProfile: "UserProfile",
  emitterProfiles: "EmitterProfile",
  tags: "Tag",
  conditionsTemplates: "ConditionsTemplate",
  fiscalSources: "FiscalSource",
  companyCategories: "CompanyCategory",
  calendarCategories: "CalendarCategory",
  expenseCategories: "ExpenseCategory",
  emailTemplates: "EmailTemplate",
  callTemplates: "CallTemplate",
  investmentPlatforms: "InvestmentPlatform",
  skills: "Skill",
  companies: "Company",
  companyTeams: "CompanyTeam",
  clients: "Client",
  interactions: "Interaction",
  reminders: "Reminder",
  clientFiles: "ClientFile",
  products: "Product",
  projects: "Project",
  milestones: "Milestone",
  taskTags: "TaskTag",
  tasks: "Task",
  timeEntries: "TimeEntry",
  journalEntries: "JournalEntry",
  deliverables: "Deliverable",
  usefulLinks: "UsefulLink",
  postDevs: "PostDev",
  renewals: "Renewal",
  quotes: "Quote",
  quoteLines: "QuoteLine",
  invoices: "Invoice",
  invoiceLines: "InvoiceLine",
  payments: "Payment",
  recurringInvoices: "RecurringInvoice",
  recurringInvoiceLines: "RecurringInvoiceLine",
  calendarEvents: "CalendarEvent",
  projectIdeas: "ProjectIdea",
  projectContacts: "ProjectContact",
  projectEvents: "ProjectEvent",
  prospectEvents: "ProspectEvent",
  prospectNotes: "ProspectNote",
  emailLogs: "EmailLog",
  emailDrafts: "EmailDraft",
  interviewAnswers: "InterviewAnswer",
  recurringRevenues: "RecurringRevenue",
  revenues: "Revenue",
  recurringExpenses: "RecurringExpense",
  expenses: "Expense",
  healthEvents: "HealthEvent",
  healthConsultations: "HealthConsultation",
  healthReimbursements: "HealthReimbursement",
  jobApplications: "JobApplication",
  jobApplicationEvents: "JobApplicationEvent",
  urssafDeclarations: "UrssafDeclaration",
  urssafDeclarationLines: "UrssafDeclarationLine",
  projectSkills: "ProjectSkill",
  jobApplicationSkills: "JobApplicationSkill",
  interviewQuestions: "InterviewQuestion",
  questionSkills: "QuestionSkill",
  investmentEntries: "InvestmentEntry",
}

export const EXCLUDED_MODELS: Record<string, string> = {
  User: "le compte lui-même (recréé par la connexion Google)",
  Account: "jetons OAuth — propres à l'installation, jamais exportés",
  Session: "sessions d'authentification",
  VerificationToken: "jetons de vérification d'authentification",
  PushSubscription: "abonnements push propres à chaque appareil",
  Notification: "notifications éphémères",
  MonitoringCheck: "historique de disponibilité régénéré par le cron",
  ProjectMember: "partage multi-comptes (références à d'autres utilisateurs)",
}
