-- AlterTable
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "address"    TEXT;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "postalCode" TEXT;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "city"       TEXT;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "country"    TEXT;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "siret"      TEXT;
